#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Uniqoders\Game\Console\GameCommand;

/**
 * Error handling
 */
try {
    $app = new Application('Rock, Paper, Scissors', '1.0.0');
    $app->add(new GameCommand);
    $app->run();
} catch (\Throwable $th) {
    print_r($th);
}
